Ottav/Ottav/Models/Study/DropDownFields.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ottav.Models.Study
{
    public class DropDownFields
    {
        public string selectedField { get; set; }

        public List<SelectListItem> DropDownListOptions = new List<SelectListItem>()
        {
            new SelectListItem { Value = "1", Text = "Option1" },
            new SelectListItem { Value = "2", Text = "Option2" },
            new SelectListItem { Value = "3", Text = "Option3" },
            new SelectListItem { Value = "4", Text = "Option4" },
        };
    }
}

Ottav/Ottav/Controllers/StudyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ottav.Models.Study;

namespace Ottav.Controllers
{
    public class StudyController : Controller
    {
        //
        // GET: Study
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: DropDownList
        public ActionResult DropDownList()
        {
            ViewBag.MoviesList = new List<SelectListItem>()
            {
                new SelectListItem { Value = "El SpiderMân!", Text = "Spider-man"  },
                new SelectListItem { Value = "This is Spaaaartaaaa", Text = "300" },
                new SelectListItem { Value = "Not the beeeeeeeeeees!!!", Text = "Wicker Man" },
                new SelectListItem { Value = "Freeeeeedoooom!!", Text = "Braveheart" }
            };

            DropDownFields fields = new DropDownFields();
            return View(fields);
        }

        //
        // POST: DropDownList
        [HttpPost]
        public ActionResult DropDownList(string optionSelect, DropDownFields fields, string MoviesList)
        {
            ViewBag.MoviesList = InitializeViewBagList();

            // <select> DropDown List

            string forma1 = optionSelect;
            string forma2 = Request["optionSelect"];
            string forma3 = Request.Form["optionSelect"];

            if (!string.IsNullOrWhiteSpace(optionSelect))
                ViewBag.optSelected = optionSelect;

            // DropDownList

            if (!string.IsNullOrEmpty(MoviesList))
            {
                ViewBag.opt2Selected = MoviesList;
            }

            // DropDownListFor
            if (!string.IsNullOrWhiteSpace(fields.selectedField))
            {
                return View(fields);
            }

            // Clear Model Fields - Form Reset;
            //ModelState.Clear();

            return View(fields);
        }

        public List<SelectListItem> InitializeViewBagList()
        {
            List<SelectListItem> list = new List<SelectListItem>()
            {
                new SelectListItem { Value = "El SpiderMân!", Text = "Spider-man"  },
                new SelectListItem { Value = "This is Spaaaartaaaa", Text = "300" },
                new SelectListItem { Value = "Not the beeeeeeeeeees!!!", Text = "Wicker Man" },
                new SelectListItem { Value = "Freeeeeedoooom!!", Text = "Braveheart" }
            };

            return list;
        }
    }
}

Ottav/Ottav/Views/Study/DropDownList.cshtml
@model Ottav.Models.Study.DropDownFields

@{
    ViewBag.Title = "Drop Down List Examples";
    ViewBag.TestVarSelOption = "Valor em ViewBag";
}

<html>
<body>
    <div class="mainContainer">
        <div class="box">
            <h1 class="page-header" style="margin: 70px 0 50px 0">@ViewBag.Title</h1>

            <h3>- By using &lt;select&gt; HTML Tags</h3>

            <form action="/Study/DropDownList" method="post">
                <select class="btn" id="optionSelect" name="optionSelect" required autofocus>
                    <option value="0">...</option>
                    <option value="http://badjoras.com">Option 1</option>
                    <option value="2" selected="selected">Option 2</option>
                    <option value=@ViewBag.TestVarSelOption>Option 3</option>
                    <option value="4">Option 4</option>
                </select>

                <input class="btn" type="submit" value="Enviar" style="margin-left:30px; width:200px" />
            </form>

            @if (ViewBag.optSelected != null)
            {
                <p style="color:red; font-weight:bolder; margin-top:20px;">Valor escolhido: @ViewBag.optSelected</p>
            }

            <br /><hr />
            <h3>- By using DropDownListFor()</h3>

            @using (Html.BeginForm("DropDownList", "Study", FormMethod.Post))
            {
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.selectedField, Model.DropDownListOptions, new { @class = "form-control" })
                </div>
                <div class="col-md-3">
                    <input class="btn" type="submit" value="Enviar" style="margin-left:30px; width:200px" />
                </div>
            }

            @if (Model.selectedField != null)
            {
                <p style="color:red; font-weight:bolder; margin-top:20px;">Valor escolhido: @Model.selectedField</p>
            }

            <hr />
            <h3>- By using DropDownList()</h3>

            @using (Html.BeginForm("DropDownList", "Study", FormMethod.Post))
            {
                // MoviesList has a double meaning:
                // - Is the key to find ViewBag.Movie IEnumerable<SelectListItem>
                // - Identifies the value returned by the form

                <div class="col-md-4">
                    @Html.DropDownList("MoviesList", null, new { @class = "btn" })
                </div>
                <div class="col-md-3">
                    <input class="btn" type="submit" value="Enviar" style="margin-left:30px; width:200px" />
                </div>
            }

            @if (Model.selectedField != null)
            {
                <p style="color:red; font-weight:bolder; margin-top:20px;">Valor escolhido: @ViewBag.opt2Selected</p>
            }
        </div>
    </div>
</body>
</html>

Ottav/Ottav/Views/Study/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>